# Generated by Django 4.2.6 on 2023-10-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('state_country', models.CharField(max_length=2, verbose_name='Sigla do Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('date_of_birth', models.DateField(verbose_name='Data de Nascimento')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city', verbose_name='Cidade')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.course', verbose_name='Curso')),
            ],
        ),
    ]
